import { BankItem } from "../models/bank.model";

export const BANKS: BankItem[] = [
  {
    name: 'TMCP Công thương Việt Nam',
    code: 'ICB',
    bin: '970415',
    short_name: 'VietinBank',
    supported: true,
  },
  {
    name: 'Ngân hàng TMCP Ngoại Thương Việt Nam',
    code: 'VCB',
    bin: '970436',
    short_name: 'Vietcombank',
    supported: true,
  },
  {
    name: 'TMCP Quân đội',
    code: 'MB',
    bin: '970422',
    short_name: 'MBBank',
    supported: true,
  },
  {
    name: 'TMCP Á Châu',
    code: 'ACB',
    bin: '970416',
    short_name: 'ACB',
    supported: true,
  },
  {
    name: 'TMCP Việt Nam Thịnh Vượng',
    code: 'VPB',
    bin: '970432',
    short_name: 'VPBank',
    supported: true,
  },
  {
    name: 'TMCP Tiên Phong',
    code: 'TPB',
    bin: '970423',
    short_name: 'TPBank',
    supported: true,
  },
  {
    name: 'Ngân hàng TMCP Hàng Hải',
    code: 'MSB',
    bin: '970426',
    short_name: 'MSB',
    supported: true,
  },
  {
    name: 'TMCP Nam Á',
    code: 'NAB',
    bin: '970428',
    short_name: 'NamABank',
    supported: false,
  },
  {
    name: 'TMCP Bưu Điện Liên Việt',
    code: 'LPB',
    bin: '970449',
    short_name: 'LienVietPostBank',
    supported: true,
  },
  {
    name: 'Ngân hàng TMCP Bản Việt',
    code: 'VCCB',
    bin: '970454',
    short_name: 'VietCapitalBank',
    supported: true,
  },
  {
    name: 'TMCP Đầu tư và Phát triển Việt Nam',
    code: 'BIDV',
    bin: '970418',
    short_name: 'BIDV',
    supported: true,
  },
  {
    name: 'TMCP Sài Gòn Thương Tín',
    code: 'STB',
    bin: '970403',
    short_name: 'Sacombank',
    supported: true,
  },
  {
    name: 'Ngân hàng TMCP Quốc tế Việt Nam',
    code: 'VIB',
    bin: '970441',
    short_name: 'VIB',
    supported: true,
  },
  {
    name: 'TMCP Phát triển Thành phố Hồ Chí Minh',
    code: 'HDB',
    bin: '970437',
    short_name: 'HDBank',
    supported: true,
  },
  {
    name: 'Ngân hàng TMCP Đông Nam Á',
    code: 'SEAB',
    bin: '970440',
    short_name: 'SeABank',
    supported: true,
  },
  {
    name: 'Thương mại TNHH MTV Dầu Khí Toàn Cầu',
    code: 'GPB',
    bin: '970408',
    short_name: 'GPBank',
    supported: false,
  },
  {
    name: 'Ngân hàng TMCP Đại Chúng Việt Nam',
    code: 'PVCB',
    bin: '970412',
    short_name: 'PVcomBank',
    supported: false,
  },
  {
    name: 'TMCP Quốc Dân',
    code: 'NCB',
    bin: '970419',
    short_name: 'NCB',
    supported: false,
  },
  {
    name: 'TNHH MTV Shinhan Việt Nam',
    code: 'SHBVN',
    bin: '970424',
    short_name: 'ShinhanBank',
    supported: true,
  },
  {
    name: 'TMCP Sài Gòn',
    code: 'SCB',
    bin: '970429',
    short_name: 'SCB',
    supported: false,
  },
  {
    name: 'TMCP Xăng dầu Petrolimex',
    code: 'PGB',
    bin: '970430',
    short_name: 'PGBank',
    supported: false,
  },
  {
    name: 'Nông nghiệp và Phát triển Nông thôn Việt Nam',
    code: 'VBA',
    bin: '970405',
    short_name: 'Agribank',
    supported: true,
  },
  {
    name: 'TMCP Kỹ thương Việt Nam',
    code: 'TCB',
    bin: '970407',
    short_name: 'Techcombank',
    supported: true,
  },
  {
    name: 'TMCP Sài Gòn Công Thương',
    code: 'SGICB',
    bin: '970400',
    short_name: 'SaigonBank',
    supported: false,
  },
  {
    name: 'TMCP Đông Á',
    code: 'DOB',
    bin: '970406',
    short_name: 'DongABank',
    supported: false,
  },
  {
    name: 'TMCP Bắc Á',
    code: 'BAB',
    bin: '970409',
    short_name: 'BacABank',
    supported: true,
  },
  {
    name: 'TNHH MTV Standard Chartered Bank Việt Nam',
    code: 'SCVN',
    bin: '970410',
    short_name: 'StandardChartered',
    supported: false,
  },
  {
    name: 'Thương mại TNHH MTV Đại Dương',
    code: 'Oceanbank',
    bin: '970414',
    short_name: 'Oceanbank',
    supported: false,
  },
  {
    name: 'Liên doanh Việt - Nga',
    code: 'VRB',
    bin: '970421',
    short_name: 'VRB',
    supported: false,
  },
  {
    name: 'TMCP An Bình',
    code: 'ABB',
    bin: '970425',
    short_name: 'ABBANK',
    supported: true,
  },
  {
    name: 'TMCP Việt Á',
    code: 'VAB',
    bin: '970427',
    short_name: 'VietABank',
    supported: false,
  },
  {
    name: 'TMCP Xuất Nhập khẩu Việt Nam',
    code: 'EIB',
    bin: '970431',
    short_name: 'Eximbank',
    supported: true,
  },
  {
    name: 'TMCP Việt Nam Thương Tín',
    code: 'VIETBANK',
    bin: '970433',
    short_name: 'VietBank',
    supported: false,
  },
  {
    name: 'TNHH Indovina',
    code: 'IVB',
    bin: '970434',
    short_name: 'IndovinaBank',
    supported: false,
  },
  {
    name: 'TMCP Bảo Việt',
    code: 'BVB',
    bin: '970438',
    short_name: 'BaoVietBank',
    supported: false,
  },
  {
    name: 'TNHH MTV Public Việt Nam',
    code: 'PBVN',
    bin: '970439',
    short_name: 'PublicBank',
    supported: true,
  },
  {
    name: 'TMCP Sài Gòn - Hà Nội',
    code: 'SHB',
    bin: '970443',
    short_name: 'SHB',
    supported: false,
  },
  {
    name: 'Thương mại TNHH MTV Xây dựng Việt Nam',
    code: 'CBB',
    bin: '970444',
    short_name: 'CBBank',
    supported: false,
  },
  {
    name: 'TMCP Phương Đông',
    code: 'OCB',
    bin: '970448',
    short_name: 'OCB',
    supported: true,
  },
  {
    name: 'TMCP Kiên Long',
    code: 'KLB',
    bin: '970452',
    short_name: 'KienLongBank',
    supported: true,
  },
  {
    name: 'TNHH MTV CIMB Việt Nam',
    code: 'CIMB',
    bin: '422589',
    short_name: 'CIMB',
    supported: false,
  },
  {
    name: 'TNHH MTV HSBC (Việt Nam)',
    code: 'HSBC',
    bin: '458761',
    short_name: 'HSBC',
    supported: false,
  },
  {
    name: 'DBS Bank Ltd - Chi nhánh Thành phố Hồ Chí Minh',
    code: 'DBS',
    bin: '796500',
    short_name: 'DBSBank',
    supported: false,
  },
  {
    name: 'Nonghyup - Chi nhánh Hà Nội',
    code: 'NHB HN',
    bin: '801011',
    short_name: 'Nonghyup',
    supported: false,
  },
  {
    name: 'TNHH MTV Hong Leong Việt Nam',
    code: 'HLBVN',
    bin: '970442',
    short_name: 'HongLeong',
    supported: false,
  },
  {
    name: 'Ngân hàng Công nghiệp Hàn Quốc - Chi nhánh Hà Nội',
    code: 'IBK',
    bin: '970455',
    short_name: 'IBK Bank',
    supported: false,
  },
  {
    name: 'TNHH MTV Woori Việt Nam',
    code: 'WVN',
    bin: '970457',
    short_name: 'Woori',
    supported: false,
  },
  {
    name: 'United Overseas - Chi nhánh TP. Hồ Chí Minh',
    code: 'UOB',
    bin: '970458',
    short_name: 'UnitedOverseas',
    supported: false,
  },
  {
    name: 'Kookmin - Chi nhánh Hà Nội',
    code: 'KBHN',
    bin: '970462',
    short_name: 'KookminHN',
    supported: false,
  },
  {
    name: 'Kookmin - Chi nhánh Thành phố Hồ Chí Minh',
    code: 'KBHCM',
    bin: '970463',
    short_name: 'KookminHCM',
    supported: false,
  },
  {
    name: 'Hợp tác xã Việt Nam',
    code: 'COOPBANK',
    bin: '970446',
    short_name: 'COOPBANK',
    supported: false,
  },
];
